project_id = "mxqsqltdwqlpgeyychhk"

[functions.submit-creator-application]
verify_jwt = false

[functions.review-creator-application]
verify_jwt = true

[functions.manage-design]
verify_jwt = true

[functions.process-creator-earnings]
verify_jwt = true

[functions.send-monthly-earnings-summary]
verify_jwt = false
